- .eslintignore
- .github/workflows/build-lint-test.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- .gitignore
- .prettierignore
- README.md
- package-lock.json
- packages/module/package.json
Completes the move from yarn to just npm, also resolves a reach/router error that I was encountering when attempting to build the docs.
I think this issue stems from a difference in how npm and yarn resolve dependency issues, and that the issue will likely be resolved on its own after switching to the latest (currently alpha) version of the documentation framework. In the meantime adding reach/router as a devDep and initially doing a force install seemed to work around the issue.
> chore(CI, packaging): Replace yarn

- packages/module/patternfly-docs/content/extensions/component-groups/examples/NotAuthorized/NotAuthorized.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/NotAuthorized/NotAuthorizedExample.tsx
- packages/module/src/NotAuthorized/NotAuthorized.tsx
- packages/module/src/NotAuthorized/__tests__/__snapshots__/NotAuthorized.test.js.snap
- packages/module/src/index.ts
[RHCLOUD-24176](https://issues.redhat.com/browse/RHCLOUD-24176)
Added NotAuthorized example
> fix(docs): Add NotAuthorized example

- packages/module/src/ErrorState/ErrorState.tsx
Added a new property for compatibility reasons with the old FEC implementation
> Add defaultErrorDescription property to ErrorState

- packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/DetailsPageExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/HorizontalNavExample.tsx
- packages/module/src/HorizontalNav/HorizontalNav.tsx
Allow the children of the tab to control the spacing so as to maintain consistency with PatternFly.
> Remove tab contents wrapper

- packages/module/src/NotAuthorized/NotAuthorized.tsx
[RHCLOUD-26913](https://issues.redhat.com/browse/RHCLOUD-26913)
Added toLandingPageUrl to NotAuthorized
> Add toLandingPageUrl to NotAuthorized

- packages/module/src/Battery/Battery.tsx
- packages/module/src/DetailsPageHeader/utils/ActionMenu.tsx
- packages/module/src/ErrorBoundary/ErrorBoundary.tsx
- packages/module/src/ErrorBoundary/ErrorStack.tsx
- packages/module/src/ErrorState/ErrorState.tsx
- packages/module/src/NotAuthorized/NotAuthorized.tsx
- packages/module/src/NotAuthorized/__snapshots__/NotAuthorized.test.tsx.snap
Renamed variables to PF v5 ones
> fix(pf5): Rename variables to PF v5 ones

- packages/module/src/ErrorBoundary/ErrorBoundary.tsx
This adds https://github.com/RedHatInsights/frontend-components/pull/1901
> Remove setState call from ErrorBoundary render fn

- packages/module/patternfly-docs/content/extensions/component-groups/examples/Battery/Battery.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/DetailsPage.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorBoundary/ErrorBoundary.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorState.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/NotAuthorized/NotAuthorized.md
> docs(extensions): Adds documentation to each component group extension.

- packages/module/patternfly-docs/content/extensions/component-groups/examples/LongTextTooltip/LongTextTooltip.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/LongTextTooltip/LongTextTooltipExample.tsx
- packages/module/src/LongTextTooltip/LongTextTooltip.test.tsx
- packages/module/src/LongTextTooltip/LongTextTooltip.tsx
- packages/module/src/LongTextTooltip/__snapshots__/LongTextTooltip.test.tsx.snap
- packages/module/src/LongTextTooltip/index.ts
- packages/module/src/index.ts
Added LongTextTooltip to component groups repo.
> feat(LongTextTooltip): Added LongTextTooltip component.

- packages/module/patternfly-docs/content/extensions/component-groups/examples/LongTextTooltip/LongTextTooltip.md
- packages/module/src/LongTextTooltip/LongTextTooltip.tsx
Updated with additional review comments, from PR #41
> fix(longtexttooltip): Updated with additional review comments.

- packages/module/patternfly-docs/content/extensions/component-groups/examples/Ansible/Ansible.md
> docs(ansible): Adjusts documentation.

- packages/module/patternfly-docs/content/extensions/component-groups/examples/WarningModal/WarningModal.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/WarningModal/WarningModalExample.tsx
- packages/module/src/WarningModal/WarningModal.test.tsx
- packages/module/src/WarningModal/WarningModal.tsx
- packages/module/src/WarningModal/__snapshots__/WarningModal.test.tsx.snap
- packages/module/src/WarningModal/index.ts
- packages/module/src/index.ts
Introducing shared components to be used across our UIs, part of [RHCLOUD-23731](https://issues.redhat.com/browse/RHCLOUD-23731)
> feat(WarningModal): Add warning modal component

- packages/module/patternfly-docs/content/extensions/component-groups/examples/WarningModal/WarningModal.md
> (docs: warning-modal) Adjusts example documentation.

- packages/module/src/UnavailableContent/UnavailableContent.tsx
- packages/module/src/UnavailableContent/__snapshots__/UnavailableContent.test.tsx.snap
[RHCLOUD-29134](https://issues.redhat.com/browse/RHCLOUD-29134)
> fix(title): Fix title in UnavailableContent

- packages/module/src/Ansible/Ansible.tsx
- packages/module/src/Ansible/__snapshots__/Ansible.test.tsx.snap
- packages/module/src/Battery/Battery.tsx
- packages/module/src/Battery/__snapshots__/Batery.test.tsx.snap
Fixed issue #58 
https://pf-component-groups-a11y.surge.sh
> Fixed a11y component issues.

- packages/module/src/Ansible/Ansible.tsx
Updates ansible color to disable 100, instead of disable 200.
> fix(ansible): Updated ansible color to address issue 74.

- packages/module/patternfly-docs/content/extensions/component-groups/examples/NotAuthorized/NotAuthorizedExample.tsx
- packages/module/src/NotAuthorized/NotAuthorized.test.tsx
- packages/module/src/NotAuthorized/NotAuthorized.tsx
- packages/module/src/NotAuthorized/__snapshots__/NotAuthorized.test.tsx.snap
Updated API to support only one primary action, and all further actions should be secondary actions.  This is to comply with PF 5 design guidelines.
> fix(notAuthorized): Updated code to support PF 5 design system with one primary action

- packages/module/src/ErrorBoundary/ErrorBoundary.tsx
- packages/module/src/ErrorStack/ErrorStack.tsx
- packages/module/src/NotAuthorized/NotAuthorized.tsx
- packages/module/src/SkeletonTable/index.ts
- packages/module/src/TagCount/TagCount.tsx
- packages/module/src/TagCount/__snapshots__/TagCount.test.tsx.snap
Part of [RHCLOUD-28988](https://issues.redhat.com/browse/RHCLOUD-28988)
- Added `iconSize` param to TagCount for compatibility with FEC
- Fixed `SkeletonTable` export
- Allowed passing className to `ErrorStack` for compatibility with FEC
- Removed extra imports
- Update primaryAction description for `NotAuthorized`
> Minor fixes and enhancements for FEC compatibility

- packages/module/src/Battery/Battery.tsx
- packages/module/src/Battery/__snapshots__/Batery.test.tsx.snap
Updated with CSS fixes for battery.
https://pf-battery.surge.sh
> fix(battery): Css fix for batteries.

- packages/module/patternfly-docs/content/extensions/component-groups/about-component-groups.md
> docs(react-component-groups): Creates overview page for extension.

- packages/module/src/ErrorBoundary/ErrorBoundary.tsx
- packages/module/src/InvalidObject/InvalidObject.tsx
- packages/module/src/UnavailableContent/UnavailableContent.tsx
Added support for i18n to Error Boundary, Inavalid Object, and Unavailable Content.
Fixes issue #52.
https://pf-localization.surge.sh/
> fix(i18n): i18n support, fixes issue #52

- packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorState.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorStateExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorStateFooterExample.tsx
- packages/module/src/ErrorState/ErrorState.test.tsx
- packages/module/src/ErrorState/ErrorState.tsx
Added custom footer option to ErrorState
> feat(customContent): Add customFooter to ErrorState

- package-lock.json
- packages/module/package.json
- packages/module/patternfly-docs/content/extensions/component-groups/examples/CloseButton/CloseButton.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/CloseButton/CloseButtonExample.tsx
- packages/module/src/CloseButton/CloseButton.tsx
- packages/module/src/CloseButton/index.ts
- packages/module/src/index.ts
Closes #87 
[RHCLOUD-30381](https://issues.redhat.com/browse/RHCLOUD-30381)
Added the close button from OpenShift.
> feat(CloseButton): Added close button from OpenShift.

- packages/module/patternfly-docs/content/extensions/component-groups/examples/CloseButton/CloseButton.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/CloseButton/CloseButtonExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorState.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/NotAuthorized/NotAuthorized.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/NotAuthorized/NotAuthorizedCustomExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/NotAuthorized/NotAuthorizedDefaultExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/WarningModal/WarningModal.md
- packages/module/src/CloseButton/CloseButton.tsx
- packages/module/src/NotAuthorized/NotAuthorized.tsx
- packages/module/src/NotAuthorized/__snapshots__/NotAuthorized.test.tsx.snap
- packages/module/src/WarningModal/WarningModal.tsx
- fixed NotAuthorized default primary actions variant to primary
- cleaned the CloseButton props
- Updated docs to contain reference to the parent components props
> Fix NotAuthorized default actions and clean the code

- packages/module/patternfly-docs/content/extensions/component-groups/examples/ShortcutGrid/ShortcutExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ShortcutGrid/ShortcutGrid.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ShortcutGrid/ShortcutGridExample.tsx
- packages/module/src/Shortcut/Shortcut.test.tsx
- packages/module/src/Shortcut/Shortcut.tsx
- packages/module/src/Shortcut/__snapshots__/Shortcut.test.tsx.snap
- packages/module/src/Shortcut/index.ts
- packages/module/src/ShortcutGrid/ShortcutGrid.test.tsx
- packages/module/src/ShortcutGrid/ShortcutGrid.tsx
- packages/module/src/ShortcutGrid/__snapshots__/ShortcutGrid.test.tsx.snap
- packages/module/src/ShortcutGrid/index.ts
- packages/module/src/index.ts
JIRA link: [RHCLOUD-30296](https://issues.redhat.com/browse/RHCLOUD-30296)
closes #93 
- added Shortcut component
- added ShortcutGrid component
- created documentation pages & tests
> Migrate Shortcut component from OpenShift console

- packages/module/patternfly-docs/content/extensions/component-groups/examples/CloseButton/CloseButton.md
Previously the docs source code link would try to link to patternfly-react which caused a broken link.
> Fix CloseButton docs link to source code

- .github/upload-preview.js
- .github/workflows/pr-preview.yml
- package-lock.json
- package.json
This PR fixes the package.json imports as well as the missing tokens.
> Fixes missing keys and packages for pr preview.

- packages/module/patternfly-docs/content/extensions/component-groups/examples/WarningModal/WarningModalCheckboxExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/WarningModal/WarningModalDangerExample.tsx
Fixed WarningModal button variant examples to show danger button variant correctly
> fix(WarningModal): Fix WarningModal button variant examples

- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCard.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableActionsExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableBorderExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableDividerExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableExample.tsx
- packages/module/src/LogSnippet/LogSnippet.tsx
- packages/module/src/MultiContentCard/MultiContentCard.test.tsx
- packages/module/src/MultiContentCard/MultiContentCard.tsx
- packages/module/src/MultiContentCard/__snapshots__/MultiContentCard.test.tsx.snap
- packages/module/src/MultiContentCard/index.ts
- packages/module/src/index.ts
closes #97 
[RHCLOUD-30683](https://issues.redhat.com/browse/RHCLOUD-30683)
Added a new MultiContentCard component to replace OpenShift and HCC implementations.
> Add OpenShift MultiContentCard (GettingStarted)

- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCard.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableBorderExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableSingleDividerExample.tsx
- packages/module/src/MultiContentCard/MultiContentCard.test.tsx
- packages/module/src/MultiContentCard/MultiContentCard.tsx
- packages/module/src/MultiContentCard/__snapshots__/MultiContentCard.test.tsx.snap
[RHCLOUD-31339](https://issues.redhat.com/browse/RHCLOUD-31339)
Allowed dividers for single content cards 
closes #120
> feat(mcc): Allow dividers for single content cards

- packages/module/patternfly-docs/content/extensions/component-groups/examples/Battery/Battery.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Battery/BatteryCriticalExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Battery/BatteryDefaultExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Battery/BatteryHighExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Battery/BatteryLowExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Battery/BatteryMediumExample.tsx
- packages/module/src/Battery/Batery.test.tsx
- packages/module/src/Battery/Battery.tsx
- packages/module/src/Battery/__snapshots__/Batery.test.tsx.snap
- packages/module/src/LogSnippet/LogSnippet.tsx
Replaced variant types with enums in LogSnippet and Battery components
- visual appearance of the components hasn't been affected
- cleaned up the BatterySeverity variants to "low", "medium", "high", "critical"
- updated tests
Screenshots:
closes #121
> Replace variant types with enums in existing components 

- .github/workflows/build-lint-test.yml
- .github/workflows/build.yml
- .github/workflows/pr-preview.yml
- .github/workflows/promote.yml
- .github/workflows/release.yml
Part of [RHCLOUD-28132](https://issues.redhat.com/browse/RHCLOUD-28132)
Updated GH actions to the latest versions and made them use node 20
> Update GH actions

- packages/module/patternfly-docs/content/extensions/component-groups/about-component-groups.md
Closes https://github.com/patternfly/patternfly-org/issues/3891
The "View source on Github" link was broken on the ["About Component Groups" Page](https://www.patternfly.org/extensions/component-groups/about-component-groups) so I added the sourceLink to the docs
> fix(docs): Update about component groups source link

- packages/module/src/WarningModal/WarningModal.tsx
[RHCLOUD-31959](https://issues.redhat.com/browse/RHCLOUD-31959)
The check state of the confirmation checkbox now correctly resets on closing the modal
> fix(WarningModal): Reset check state on close

- packages/module/src/ErrorBoundary/ErrorBoundary.tsx
- packages/module/src/ErrorState/ErrorState.tsx
closes #132 
[RHCLOUD-32155](https://issues.redhat.com/browse/RHCLOUD-32155)
Aligned "Show details" center to prevent it from changing position on click
Before:
Now:
> fix(ErrorBoundary): Align "Show details" center

- packages/module/patternfly-docs/content/extensions/component-groups/examples/ColumnManagementModal/ColumnManagementModal.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ColumnManagementModal/ColumnManagementModalExample.tsx
- packages/module/src/ColumnManagementModal/ColumnManagementModal.test.tsx
- packages/module/src/ColumnManagementModal/ColumnManagementModal.tsx
- packages/module/src/ColumnManagementModal/index.ts
- packages/module/src/index.ts
Associated ticket: [RHINENG-3003](https://issues.redhat.com/browse/RHINENG-3003)
Implement a modal that a user can use to configure the visibility of individual table columns. The modal supports columns that are hidden by default and also those that should be unhideable.
[Screencastfrom2024-04-1216-04-18-ezgif.com-video-to-gif-converter.webm](https://github.com/patternfly/react-component-groups/assets/8426204/268280f5-357e-48f1-a780-cb26b339bfef)
Since there is a request (see the associated ticket above) to implement column management in tables in all apps across Insights it would make sense to abstract a component that could be reused. Currently, the only implementation of column management is in [Insights Vulnerability](https://console.redhat.com/insights/vulnerability) (hidden inside …
> feat: Add new Column Management Modal component

- cypress/component/Ansible.cy.tsx
- cypress/component/CloseButton.cy.tsx
- cypress/component/ErrorBoundary.cy.tsx
- cypress/component/ErrorBoundry.cy.tsx
- cypress/component/ErrorState.cy.tsx
- cypress/component/InvalidObject.cy.tsx
- cypress/component/LogSnippet.cy.tsx
- cypress/component/MultiContentCard.cy.tsx
- cypress/component/NotAuthorized.cy.tsx
- cypress/component/ShortcutGrid.cy.tsx
- cypress/component/SkeletonTable.cy.tsx
- cypress/component/TagCount.cy.tsx
- cypress/component/UnavailableContent.cy.tsx
- cypress/component/WarningModal.cy.tsx
part of [RHCLOUD-31955](https://issues.redhat.com/browse/RHCLOUD-31955)
> add basic component cypress tests

- cypress/component/SkeletonTable.cy.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Skeleton/Skeleton.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Skeleton/SkeletonTableCompactExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Skeleton/SkeletonTableCustomExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Skeleton/SkeletonTableExpandableExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Skeleton/SkeletonTableSelectableExample.tsx
- packages/module/src/SkeletonTable/SkeletonTable.tsx
- packages/module/src/SkeletonTable/__snapshots__/SkeletonTable.test.tsx.snap
Added the following props to the SkeletonTable component ([RHCLOUD-32382](https://issues.redhat.com/browse/RHCLOUD-32382)):
- `isSelectable`: A boolean prop that determines whether the table rows are selectable. When set to true, checkboxes will be rendered in a column to the left side.
- `isExpandable`: A boolean prop that indicates whether the table rows are expandable. When set to true, a caret expand indicator will be rendered in a column to the left side.
- `sortBy`: An object that specifies the sort column and direction for the table. It has the following shape:
```
{
index: number;
direction: 'asc' | 'desc';
}
```
- `index` represents the index of the column to sort by.
- `direction` indicates the sort direction, either `'asc'` for ascending order or `'desc'` for descending order.
> Add props for sort indicators, checkboxes and expand to Skeleton Table

- cypress/component/Status.cy.tsx
- cypress/e2e/CloseButton.spec.cy.ts
- package-lock.json
- packages/module/package.json
- packages/module/patternfly-docs/content/extensions/component-groups/examples/CloseButton/CloseButton.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Status/IconOnlyStatusExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Status/LinkStatusExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Status/PopoverStatusExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Status/Status.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Status/StatusDescriptionExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/Status/StatusExample.tsx
- packages/module/src/Status/Status.test.tsx
- packages/module/src/Status/Status.tsx
- packages/module/src/Status/__snapshots__/Status.test.tsx.snap
- packages/module/src/Status/index.tsx
finishing https://github.com/patternfly/react-component-groups/pull/125
closes #94 
[RHCLOUD-30295](https://issues.redhat.com/browse/RHCLOUD-30295)
- added OpenShift Status component
- fixed CloseButton ID in the docs
> feat(Status): Add Status component

- cypress/component/BulkSelect.cy.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/BulkSelect/BulkSelect.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/BulkSelect/BulkSelectAllExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/BulkSelect/BulkSelectExample.tsx
- packages/module/src/BulkSelect/BulkSelect.test.tsx
- packages/module/src/BulkSelect/BulkSelect.tsx
- packages/module/src/BulkSelect/__snapshots__/BulkSelect.test.tsx.snap
- packages/module/src/BulkSelect/index.ts
- packages/module/src/index.ts
[RHCLOUD-33144](https://issues.redhat.com/browse/RHCLOUD-33144)
Added BulkSelect component to component groups with docs and tests
> Add BulkSelect component

- cypress/component/BulkSelect.cy.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/BulkSelect/BulkSelectAllExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/BulkSelect/BulkSelectExample.tsx
- packages/module/src/BulkSelect/BulkSelect.tsx
- packages/module/src/BulkSelect/__snapshots__/BulkSelect.test.tsx.snap
[RHCLOUD-33417](https://issues.redhat.com/browse/RHCLOUD-33417)
Made "X selected" part of BulkSelect work the same way as the menu toggle. Also updated the example logic to work properly for select page
> Make "X selected" part of BulkSelect clickable 

- cypress/component/ErrorBoundary.cy.tsx
- cypress/component/MultiContentCard.cy.tsx
- cypress/component/WarningModal.cy.tsx
- cypress/support/component.ts
- packages/module/src/BulkSelect/__snapshots__/BulkSelect.test.tsx.snap
for [RHCLOUD-32488](https://issues.redhat.com/browse/RHCLOUD-32488)
- Adds remaining cypress component tests from the [ test plan](https://docs.google.com/document/d/11iSSGWuEeTovXE-JDIOkAFHUdt8hA2viNJS7we5xao0/edit). 
- updated the config so that error components don't cause tests to fail when throwing errors.
> Enhance component cypress tests

- README.md
- cypress/component/MultiContentCard.cy.tsx
- package-lock.json
- packages/module/package.json
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableActionsExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableDividerExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableSingleDividerExample.tsx
- packages/module/src/BulkSelect/__snapshots__/BulkSelect.test.tsx.snap
- packages/module/src/ColumnManagementModal/ColumnManagementModal.tsx
- packages/module/src/ContentHeader/ContentHeader.tsx
- packages/module/src/ContentHeader/__snapshots__/ContentHeader.test.tsx.snap
- packages/module/src/DetailsPageHeader/DetailsPageHeader.tsx
- packages/module/src/ErrorStack/ErrorStack.tsx
- packages/module/src/InvalidObject/__snapshots__/InvalidObject.test.tsx.snap
- packages/module/src/MultiContentCard/MultiContentCard.test.tsx
- packages/module/src/MultiContentCard/__snapshots__/MultiContentCard.test.tsx.snap
- packages/module/src/NotAuthorized/__snapshots__/NotAuthorized.test.tsx.snap
- packages/module/src/Status/Status.tsx
- packages/module/src/Status/__snapshots__/Status.test.tsx.snap
- packages/module/src/TagCount/__snapshots__/TagCount.test.tsx.snap
- packages/module/src/UnavailableContent/__snapshots__/UnavailableContent.test.tsx.snap
- packages/module/src/WarningModal/__snapshots__/WarningModal.test.tsx.snap
[RHCLOUD-34274](https://issues.redhat.com/browse/RHCLOUD-34274)
Updated to the latest PF versions
> Update to the latest PF versions

- packages/module/src/TagCount/TagCount.tsx
[RHINENG-7746](https://issues.redhat.com/browse/RHINENG-7746)
The tag number and icon seems to be misaligned and font-size is off in the context of surrounding content. 
Before:
fontSize: 16px
margin: 10px
After:
fontSize: 14px
margin: 6px
Any changes or improvements to this PR are welcome.
> Margin and fontSize alignment of TagCount

- packages/module/src/Status/Status.tsx
- packages/module/src/Status/__snapshots__/Status.test.tsx.snap
Jira: https://issues.redhat.com/browse/RHCLOUD-34198
https://github.com/patternfly/react-component-groups/issues/218
- Top align status icon
- Set padding to 8px
Old
New
> Status styling fixes

- packages/module/src/TagCount/TagCount.tsx
- packages/module/src/TagCount/__snapshots__/TagCount.test.tsx.snap
[RHCLOUD-34197](https://issues.redhat.com/browse/RHCLOUD-34197)
closes #219 
Fixed TagCount styling
> Fix TagCount styling

- packages/module/src/UnavailableContent/UnavailableContent.tsx
- packages/module/src/UnavailableContent/__snapshots__/UnavailableContent.test.tsx.snap
https://issues.redhat.com/browse/RHCLOUD-34196
closes #220 
Removed link button and replaced by primary button. Button was moved to the Footer section. Removed unnecessary styling.
> Unavalable Content button change

- packages/module/patternfly-docs/content/extensions/component-groups/examples/ServiceCard/ServiceCard.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ServiceCard/ServiceCardGalleryExample.tsx
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ServiceCard/ServiceCardStackedExample.tsx
- packages/module/src/ServiceCard/ServiceCard.test.tsx
- packages/module/src/ServiceCard/ServiceCard.tsx
- packages/module/src/ServiceCard/__snapshots__/ServiceCard.test.tsx.snap
[RHCLOUD-34551](https://issues.redhat.com/browse/RHCLOUD-34551)
- added horizontal header layout to the ServiceCard
- added isFullHeight option
> fix(ServiceCard): Add horizontal layout to the ServiceCard

- packages/module/src/ServiceCard/ServiceCard.tsx
There are use cases when `subtitle` prop is not needed so I'm making it optional
> make ServiceCard subtitle prop optional

- README.md
Minor README update to trigger a bugfix release
> fix(pf6): Update README.md

- packages/module/src/ColumnManagementModal/ColumnManagementModal.tsx
closes #201 
[RHCLOUD-34205](https://issues.redhat.com/browse/RHCLOUD-34205)
Fixed Column management modal actions gap
The font width looks correct already
> fix: Update ColumnManagementModal styling

- packages/module/src/ContentHeader/ContentHeader.tsx
[RHCLOUD-35306](https://issues.redhat.com/browse/RHCLOUD-35306)
Fixed content header margin and component to `<a>` by default
Before:
Now:
> Fix content header margin and component

- README.md
> fix(README): Update README.md

- packages/module/src/BulkSelect/BulkSelect.tsx
[RHCLOUD-35423](https://issues.redhat.com/browse/RHCLOUD-35423).
Fixed BulkSelect being checked when there are no rows
> fix(BulkSelect): Fix BulkSelect checked when there are no rows

- package-lock.json
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorState.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorStateExtraProps.tsx
- packages/module/src/ErrorBoundary/ErrorBoundary.tsx
- packages/module/src/ErrorState/ErrorState.test.tsx
- packages/module/src/ErrorState/ErrorState.tsx
- packages/module/src/Maintenance/Maintenance.tsx
- packages/module/src/MissingPage/MissingPage.tsx
- packages/module/src/UnauthorizedAccess/UnauthorizedAccess.tsx
- packages/module/src/UnavailableContent/UnavailableContent.tsx
- packages/module/src/index.ts
Closes: https://github.com/patternfly/react-component-groups/issues/437
Closes: https://github.com/patternfly/react-component-groups/issues/438
I still want to add the headingLevel enhancement to the other related component groups like UnauthorizedAccess
> feat(ErrorState): add some customization capabilities

- config/setupTests.js
- packages/module/patternfly-docs/content/extensions/component-groups/examples/ResponsiveActions/ResponsiveActionsExample.tsx
- packages/module/src/ResponsiveActions/ResponsiveActions.tsx
[RHCLOUD-36438](https://issues.redhat.com/browse/RHCLOUD-36438)
Fixed hiding actions dropdown when it is empty
> Hide actions dropdown when empty

- packages/module/patternfly-docs/content/extensions/component-groups/examples/ResponsiveActions/ResponsiveActionsExample.tsx
- packages/module/src/ResponsiveActions/ResponsiveActions.tsx
Fixed disabling collapsed actions in ResponsiveActions
> fix: fix disabling collapsed actions

- packages/module/src/ContentHeader/ContentHeader.tsx
[RHCLOUD-37243](https://issues.redhat.com/browse/RHCLOUD-37243)
Made content header `subtitle` prop optional
> fix: make content header subtitle optional

- package-lock.json
- packages/module/src/ContentHeader/ContentHeader.tsx
[RHCLOUD-37293](https://issues.redhat.com/browse/RHCLOUD-37293)
Allow React node in ContentHeader
> fix: allow React node in ContentHeader

- cypress/component/WarningModal.cy.tsx
- package-lock.json
- packages/module/patternfly-docs/content/extensions/component-groups/examples/WarningModal/WarningModal.md
- packages/module/patternfly-docs/content/extensions/component-groups/examples/WarningModal/WarningModalTextConfirmationExample.tsx
- packages/module/src/WarningModal/WarningModal.tsx
- packages/module/src/WarningModal/__snapshots__/WarningModal.test.tsx.snap
for [RHCLOUD-36638](https://issues.redhat.com/browse/RHCLOUD-36638): adds a text confirmation option to the Warning Modal
> feat(WarningModal): add text confirmation option

- packages/module/src/ErrorBoundary/ErrorBoundary.tsx
- packages/module/src/ErrorState/ErrorState.tsx
- packages/module/src/LogSnippet/LogSnippet.tsx
- packages/module/src/Maintenance/Maintenance.tsx
- packages/module/src/MissingPage/MissingPage.tsx
- packages/module/src/MultiContentCard/MultiContentCard.tsx
- packages/module/src/PageHeader/PageHeader.tsx
- packages/module/src/ServiceCard/ServiceCard.tsx
- packages/module/src/Severity/Severity.tsx
- packages/module/src/Status/Status.tsx
- packages/module/src/UnauthorizedAccess/UnauthorizedAccess.tsx
- packages/module/src/UnavailableContent/UnavailableContent.tsx
- packages/module/src/WarningModal/WarningModal.tsx
When trying to migrate to PF6 we found an issue with `PageHeader` component not accepting ReactNode props. This breaks our types since we want to use loading stripes in this component when the content is being loaded. Upon further investigation I found out the types were like this for a couple of our components so I adjusted the string props where it was logical to have ReactNode.
> fix(props): of some components to consume ReactNode

- packages/module/src/PageHeader/PageHeader.tsx
fixes excess spacing in breadcrumbs in PageHeader component group. also makes all props optional--OCP has a usecase where no props are passed to the PageHeader, so it should render as a regular PageSection in this case.
> fix(PageHeader): reduce margins in breadcrumb

- packages/module/src/PageHeader/PageHeader.tsx
In OpenShift console, we need the ability to turn off the bottom margin on the `<h1>`.  See https://github.com/openshift/console/pull/14965#pullrequestreview-2769260754
cc: @logonoff, @nicolethoen
> fix(PageHeader) Add the option to change the classname applied to the h1

- packages/module/src/PageHeader/PageHeader.tsx
fixes issue where the `pf-v6-u-mb-sm` helper class exists when no subtitle is given, which results in extra margin below the PageHeader when there shouldn't be.
> fix(PageHeader): remove extra padding class when no subtitle is defined
