patternfly/react-component-groups

README.md, package.json, packages/module/package.json, packages/module/patternfly-docs/content/extensions/extended-components/design-guidelines/design-guidelines.md, packages/module/patternfly-docs/content/extensions/extended-components/examples/ErrorStateExample.tsx, packages/module/patternfly-docs/content/extensions/extended-components/examples/Examples.md
Updated the repo name and package name based on conversations with team members.
=> fix(infrastructure): Renamed repo to react component groups

package-lock.json, packages/module/package.json
Fixed dependecy issues with package and pulling it into another project.
=> fix(dependencies): Fixed dependecy issues with package

packages/module/patternfly-docs/content/extensions/component-groups/examples/TagCount/TagCount.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/TagCount/TagCountDisabledExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/TagCount/TagCountExample.tsx, packages/module/src/TagCount/TagCount.test.tsx, packages/module/src/TagCount/TagCount.tsx, packages/module/src/TagCount/__snapshots__/TagCount.test.tsx.snap, packages/module/src/TagCount/index.ts, packages/module/src/index.ts
Added the tag count component.
https://pf-tag-count.surge.sh
=> feat(tagCount):  Added tag count component.

package-lock.json, packages/module/package.json, packages/module/src/SkeletonTable/__snapshots__/SkeletonTable.test.tsx.snap, packages/module/src/WarningModal/__snapshots__/WarningModal.test.tsx.snap
closes https://github.com/patternfly/react-component-groups/issues/68
Moved `clsx` and `patternfly/react-table` to dependencies, updated package versions.
=> Fix dependencies

packages/module/patternfly-docs/content/extensions/component-groups/examples/Ansible/Ansible.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/Battery/Battery.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/DetailsPage.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorBoundary/ErrorBoundary.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorState.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/InvalidObject/InvalidObject.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/NotAuthorized/NotAuthorized.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/Skeleton/Skeleton.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/TagCount/TagCount.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/Unavailable/UnavailableContent.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/WarningModal/WarningModal.md
Closes https://github.com/patternfly/patternfly-org/issues/3832
=> fix(docs): Update source link for docs

packages/module/patternfly-docs/content/extensions/component-groups/about-component-groups.md
=> fix(docs): Update migration guide link

.github/workflows/pr-preview.yml
=> Pr preview a11y fix.

.github/workflows/extensions.yml
Updated extensions action to add to issues to the [PF-Issues](https://github.com/orgs/patternfly/projects/7) project.
=> chore(pf-issues): Updated to github actions to add to PF Issues Project.

packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorStateExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/ErrorState/ErrorStateFooterExample.tsx
Fixed ErrorState examples to use the changed API, not he v5 one
=> fix(docs): Fix ErrorState examples

README.md
Trigger a new v5 version release
=> fix(readme): Update README.md

packages/module/release.config.js
Turned on dry to test fix for semantic release.
=> fix(semantic-release): Turned on dry run to test tag update for semantic release.

packages/module/release.config.js
=> fix(release): Disable dry run and release v6.

cypress/component/MultiContentCard.cy.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCard.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableActionsExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableDividerExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/MultiContentCard/MultiContentCardExpandableSingleDividerExample.tsx, packages/module/src/MultiContentCard/MultiContentCard.test.tsx, packages/module/src/MultiContentCard/MultiContentCard.tsx, packages/module/src/MultiContentCard/__snapshots__/MultiContentCard.test.tsx.snap
[RHCLOUD-34201](https://issues.redhat.com/browse/RHCLOUD-34201)
closes #215 
Updated classnames and tokens as mentioned in the issue
=> Improve MultiContentCard for v6

packages/module/release.config.js
Turn off dry so we can release version 14.
=> fix: Turned off dry run to release v6-prerelease-14

package.json, packages/module/package.json, packages/module/src/BulkSelect/BulkSelect.tsx, packages/module/src/ColumnManagementModal/ColumnManagementModal.tsx, packages/module/src/MultiContentCard/__snapshots__/MultiContentCard.test.tsx.snap, packages/module/src/TagCount/__snapshots__/TagCount.test.tsx.snap, packages/module/src/WarningModal/__snapshots__/WarningModal.test.tsx.snap, packages/module/src/index.ts, yarn.lock
Closes https://github.com/patternfly/patternfly-extension-issues/issues/75
=> feat(ver): update to rc versions

packages/module/src/SkeletonTable/SkeletonTable.tsx
=> Fix skeleton table prop name

cypress/component/ResponsiveActions.cy.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/ResponsiveActions/ResponsiveActions.md, packages/module/patternfly-docs/content/extensions/component-groups/examples/ResponsiveActions/ResponsiveActionsBreakpointExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/ResponsiveActions/ResponsiveActionsExample.tsx, packages/module/src/ResponsiveAction/ResponsiveAction.tsx, packages/module/src/ResponsiveAction/index.ts, packages/module/src/ResponsiveActions/ResponsiveActions.test.tsx, packages/module/src/ResponsiveActions/ResponsiveActions.tsx, packages/module/src/ResponsiveActions/__snapshots__/ResponsiveActions.test.tsx.snap, packages/module/src/ResponsiveActions/index.ts, packages/module/src/SkeletonTable/__snapshots__/SkeletonTable.test.tsx.snap, packages/module/src/SkeletonTableHead/__snapshots__/SkeletonTableHead.test.tsx.snap, packages/module/src/index.ts
[RHCLOUD-32489](https://issues.redhat.com/browse/RHCLOUD-32489)
Added ResponsiveActions component allowing displaying actions in a responsive view
=> Add ResponsiveActions component

package-lock.json, packages/module/package.json, packages/module/src/BulkSelect/BulkSelect.tsx, packages/module/src/BulkSelect/__snapshots__/BulkSelect.test.tsx.snap, packages/module/src/MultiContentCard/__snapshots__/MultiContentCard.test.tsx.snap, packages/module/src/ResponsiveActions/ResponsiveActions.tsx, packages/module/src/ResponsiveActions/__snapshots__/ResponsiveActions.test.tsx.snap
=> fix(menu): Fix MenuToggle ouiaIds

packages/module/src/ResponsiveAction/ResponsiveAction.tsx
Do not return null in ResponsiveActions. It broke the component to be displayed in the docs
=> fix(actions): Do not return null

packages/module/src/ContentHeader/ContentHeader.tsx
Allow children in ContentHeader
cc @radekkaluzik
=> fix(ContentHeader): Allow children in ContentHeader

package-lock.json, packages/module/patternfly-docs/content/extensions/component-groups/examples/ResponsiveActions/ResponsiveActionsExample.tsx, packages/module/src/ResponsiveActions/ResponsiveActions.tsx, packages/module/src/WarningModal/__snapshots__/WarningModal.test.tsx.snap
[RHCLOUD-37043](https://issues.redhat.com/browse/RHCLOUD-37043)
Fixed disabling collapsed actions in ResponsiveActions
=> fix: fix disabling collapsed actions

packages/module/src/ContentHeader/ContentHeader.tsx
[RHCLOUD-37293](https://issues.redhat.com/browse/RHCLOUD-37293)
Allow React node in ContentHeader
=> fix: allow React node in ContentHeader

package-lock.json, packages/module/patternfly-docs/content/extensions/component-groups/examples/PageHeader/PageHeaderBreadcrumbExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/ServiceCard/ServiceCardExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/ServiceCard/ServiceCardGalleryExample.tsx, packages/module/patternfly-docs/content/extensions/component-groups/examples/ServiceCard/ServiceCardStackedExample.tsx
closes https://github.com/patternfly/react-component-groups/issues/436
fixed links in the PageHeader and ServiceCard components
Before:
Now:
=> Fix PageHeader and ServiceCard links

README.md
Closes https://github.com/patternfly/pf-roadmap/issues/257
=> docs: Update README to include guidance for AI generated code.
